version: '2'
services:
  registry:
    image: registry:2
    environment:
      - REGISTRY_STORAGE=s3
      - REGISTRY_STORAGE_S3_REGION=${REGION}
      - REGISTRY_STORAGE_S3_BUCKET=${BUCKET}
      - REGISTRY_STORAGE_S3_ACCESSKEY=${AWS_ACCESS_KEY}
      - REGISTRY_STORAGE_S3_SECRETKEY=${AWS_SECRET_ACCESS_KEY}
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/server.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/server.key
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
    ports:
      - 5000:5000
    volumes:
      - ${HOST_CERT_LOCATION}:/certs:ro
      - ${HOST_AUTH_DATA_LOCATION}:/auth:ro
