global:
  smtp_smarthost: smtp:25
  smtp_from: exclusive.cipher+alertmanager@gmail.com
  # smtp_auth_username: 'alertmanager'
  # smtp_auth_password: 'password'

# templates:
# - '/etc/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 1m
  group_interval: 5m
  repeat_interval: 1h
  receiver: admin

inhibit_rules:
- source_match:
    severity: critical
  target_match:
    severity: warning
  equal: ['alertname', 'cluster', 'service']

receivers:
- name: admin
  email_configs:
    - from: exclusive.cipher+alertmanager@gmail.com
      to: exclusive.cipher+alertmanager@gmail.com
      send_resolved: true
