global:
  slack_api_url: <slack_url>

# templates:
# - '/etc/alertmanager/template/*.tmpl'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 1m
  group_interval: 5m
  repeat_interval: 1h
  receiver: admin

# inhibit_rules:
# - source_match:
#     severity: critical
#   target_match:
#     severity: warning
#   equal: ['alertname', 'cluster', 'service']

receivers:
- name: admin
  slack_configs:
    - send_resolved: true
      channel: general
