version: '3.3'

services:
  reverse_proxy:
    image: nginx:1.15.5-alpine
    container_name: reverse_proxy
    depends_on:
      - wekan
      - dokuwiki
    restart: always
    volumes:
     - ./nginx_configs/nginx.conf:/etc/nginx/nginx.conf:ro
     - ${CERTS_LOCATION}:/certs/:ro
     # Enabled sites
     - ./nginx_configs/wekan.conf:/etc/nginx/sites-enabled/wekan.conf:ro
     - ./nginx_configs/dokuwiki.conf:/etc/nginx/sites-enabled/dokuwiki.conf:ro
    ports:
     - 80:80
     - 443:443
    networks:
      - general
  wekandb:
    image: mongo:3.6.2
    container_name: wekandb
    restart: always
    command: mongod --smallfiles --oplogSize 128
    networks:
      - general
    expose:
      - 27017
    volumes:
      - ${WEKAN_DB_LOCAL}:/data/db
      - ${WEKAN_DUMP_LOCAL}:/data/db/dumps

  wekan:
    depends_on:
      - wekandb
    image: quay.io/wekan/wekan:v1.69
    container_name: wekan
    restart: always
    networks:
      - general
    expose:
      - 8080
    environment:
      - MONGO_URL=mongodb://wekandb:27017/wekan
      - ROOT_URL=https://portal/wekan

  dokuwiki:
    build:
      context: ./dokuwiki
    container_name: dokuwiki
    restart: always
    expose:
      - 80
    volumes:
      - ${DOKUWIKI_STORAGE_LOCAL}/dokuwiki/data:/var/www/html/dokuwiki/data
      - ${DOKUWIKI_STORAGE_LOCAL}/dokuwiki/conf:/var/www/html/dokuwiki/conf
    networks:
      - general

networks:
  general:
    driver: bridge
