version: '3.7'

services:
  reverse_proxy:
    image: nginx:1.17.8-alpine
    container_name: reverse_proxy
    depends_on:
      - wekan
      - dokuwiki
      - freshrss
    restart: always
    volumes:
     - ./nginx_configs/nginx.conf:/etc/nginx/nginx.conf:ro
     - ${CERTS_LOCATION}:/certs/:ro
     # Default splash page
     - ./nginx_configs/index.html:/usr/share/nginx/html/index.html:ro
     # Enabled sites
     - ./nginx_configs/wekan.conf:/etc/nginx/sites-enabled/wekan.conf:ro
     - ./nginx_configs/dokuwiki.conf:/etc/nginx/sites-enabled/dokuwiki.conf:ro
     - ./nginx_configs/freshrss.conf:/etc/nginx/sites-enabled/freshrss.conf:ro
    ports:
     - 80:80
     - 443:443
    networks:
      - external
      - internal

  wekandb:
    image: mongo:4.2.2
    container_name: wekandb
    restart: always
    command: mongod --oplogSize 128
    networks:
      - internal
    expose:
      - 27017
    volumes:
      - ${WEKAN_DB_LOCAL}:/data/db
      - ${WEKAN_DUMP_LOCAL}:/data/db/dumps
  wekan:
    depends_on:
      - wekandb
    image: quay.io/wekan/wekan:v3.79
    container_name: wekan
    restart: always
    networks:
      - internal
    expose:
      - 8080
    environment:
      # . after URL required for proper npm DNS resolution... it seems
      - MONGO_URL=mongodb://wekandb.:27017/wekan
      - ROOT_URL=https://portal/wekan

  dokuwiki:
    build:
      context: ./dokuwiki
    container_name: dokuwiki
    restart: always
    expose:
      - 80
    volumes:
      - ${DOKUWIKI_STORAGE_LOCAL}/dokuwiki/data:/var/www/html/dokuwiki/data
      - ${DOKUWIKI_STORAGE_LOCAL}/dokuwiki/conf:/var/www/html/dokuwiki/conf
    networks:
      - internal

  freshrss:
    container_name: freshrss
    image: freshrss/freshrss:1.15.3-alpine
    restart: always
    logging:
      options:
        max-size: 10m
    volumes:
      - freshrss-data:/var/www/FreshRSS/data
    environment:
      CRON_MIN: "4,34"
      TZ: Australia/Sydney
    networks:
      - internal
    expose:
      - 80
    # TODO Temporary measure until I have SAN certs and/or confirm any other required fixes the issues with apps access
    ports:
      - 8080:80

volumes:
  freshrss-data:

networks:
  external:
    driver: bridge
    labels:
      - "com.nginx_reverse_proxy.description=Used for containers that require external access"
  internal:
    driver: overlay
    labels:
      - "com.nginx_reverse_proxy.description=Used for containers that require only internal access"
