version: '3.7'

services:
  coredns:
    image: coredns/coredns
    container_name: coredns
    restart: always
    command: -conf /root/coredns/Corefile
    volumes:
      - ./zonefiles/:/root/coredns/zones/:ro
      - ./Corefile:/root/coredns/Corefile:ro
    ports:
     - 5300:5300/udp
     - 9153:9153/udp
     - 8181:8181
     - 10053:53/udp
     - 8880:8080
    networks:
      - general

networks:
  general:
    driver: bridge
